name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19"

      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Run Build
        run: npm run build

      - name: Run SonarCloud Scan
        env:
          ADMIN_SONAR_TOKEN: ${{ secrets.ADMIN_SONAR_TOKEN }}
        run: |
          sonar-scanner -Dsonar.projectKey=RemiLisciandra_ecommerce-admin-breizhsport -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$ADMIN_SONAR_TOKEN

      - name: Install JFrog CLI
        run: curl -fL https://getcli.jfrog.io | sh

      - name: Configure JFrog CLI
        run: ./jfrog rt c add --url ${{ secrets.JF_URL }} --access-token ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Publish Artifacts to JFrog Artifactory
        run: ./jfrog rt u ".next/*" "repo-npm/"

      - name: Publish Package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
